export { default as Navbar } from './Navbar/Navbar'
export { default as Loader } from './Loader/Loader'
export { default as Main } from './Main/Main'
export { default as Footer } from './Footer/Footer'
export { default as Rewards } from './Rewards/Rewards'
export { default as Contact } from './Contact/Contact'
export { default as About } from './About/About'